#!/bin/sh

touch_dot_revision() {
  # svnwcsub won't touch the working copy again while this hook is running
  /bin/rm -f "$WCROOT"/.revision && echo "$REVNUM" > "$WCROOT"/.revision
}

main() {
  MODE="$1"
  WCROOT="$2"
  # Don't touch gitwcsub/.asf.yaml checkouts, period.
  if [ -d "$WCROOT/.git" ] ; then
    echo "$WCROOT is a git repository, do not check out svn here!"
    exit 1
  fi
  
  if [ x"$MODE" = x"post-update" ] ; then
    REVNUM="$3"
    URL="$4"
    touch_dot_revision
  fi

  if [ x"$MODE" = x"boot" ] ; then
    REVNUM="$3"
    URL="$4"
    touch_dot_revision
  fi
}

main "$@"
